databases:
  - name: eyefoncier-db
    plan: free
    databaseName: eyefoncier
    postgresMajorVersion: "16"
    ipAllowList: []

services:
  - type: web
    name: eye-foncier
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eyefoncier-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: WEB_CONCURRENCY
        value: "4"
