# Generated by Django 5.1.15 on 2026-04-16 20:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecureDocumentLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="Token aléatoire sécurisé (secrets.token_urlsafe)",
                        max_length=64,
                        unique=True,
                        verbose_name="token",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="expire le")),
                (
                    "access_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="nombre d'accès"
                    ),
                ),
                (
                    "max_accesses",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Le lien devient invalide après ce nombre d'accès",
                        verbose_name="accès maximum",
                    ),
                ),
                (
                    "is_revoked",
                    models.BooleanField(
                        default=False,
                        help_text="Révocation manuelle par un administrateur",
                        verbose_name="révoqué",
                    ),
                ),
                (
                    "accessed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="dernier accès le"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secure_links",
                        to="documents.parcelledocument",
                        verbose_name="document",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="secure_document_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="destinataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lien document sécurisé",
                "verbose_name_plural": "Liens documents sécurisés",
                "ordering": ["-created_at"],
            },
        ),
    ]
