# Generated by Django 5.1.15 on 2026-04-16 20:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notificationlog_notification_priority_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="consent_given_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Horodatage de l'accord pour audit ARTCI",
                null=True,
                verbose_name="date du consentement",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="marketing_consent",
            field=models.BooleanField(
                default=False,
                help_text="Accepte de recevoir newsletters et offres commerciales",
                verbose_name="consentement marketing",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="sms_consent",
            field=models.BooleanField(
                default=False,
                help_text="L'utilisateur a donné son consentement pour recevoir des SMS",
                verbose_name="consentement SMS",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="unsubscribe_token",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Token pour désinscription en un clic depuis les emails",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="token de désinscription",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("transaction_status", "Statut transaction"),
                    ("payment_confirmed", "Paiement confirmé"),
                    ("payment_received", "Paiement reçu"),
                    ("payment_reminder", "Rappel de paiement"),
                    ("escrow_update", "Mise à jour séquestre"),
                    ("scoring_update", "Mise à jour scoring"),
                    ("verification_requested", "Demande de vérification"),
                    ("verification_completed", "Vérification terminée"),
                    ("parcelle_published", "Parcelle publiée"),
                    ("parcelle_validated", "Parcelle validée"),
                    ("parcelle_rejected", "Parcelle rejetée"),
                    ("parcelle_interest", "Intérêt pour une parcelle"),
                    ("match_found", "Correspondance trouvée"),
                    ("visit_request", "Demande de visite"),
                    ("visit_confirmed", "Visite confirmée"),
                    ("new_message", "Nouveau message"),
                    ("new_review", "Nouvel avis"),
                    ("client_request", "Demande client"),
                    ("kyc_update", "Mise à jour KYC"),
                    ("document_ready", "Document disponible"),
                    ("account_update", "Mise à jour compte"),
                    ("welcome", "Bienvenue"),
                    ("inactivity_reminder", "Rappel inactivité"),
                    ("newsletter", "Newsletter"),
                    ("system", "Système"),
                ],
                max_length=30,
                verbose_name="type",
            ),
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.SlugField(
                        help_text="Identifiant unique, ex : verification_clean_fomo",
                        max_length=100,
                        unique=True,
                        verbose_name="nom interne",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("transaction_status", "Statut transaction"),
                            ("payment_confirmed", "Paiement confirmé"),
                            ("payment_received", "Paiement reçu"),
                            ("payment_reminder", "Rappel de paiement"),
                            ("escrow_update", "Mise à jour séquestre"),
                            ("scoring_update", "Mise à jour scoring"),
                            ("verification_requested", "Demande de vérification"),
                            ("verification_completed", "Vérification terminée"),
                            ("parcelle_published", "Parcelle publiée"),
                            ("parcelle_validated", "Parcelle validée"),
                            ("parcelle_rejected", "Parcelle rejetée"),
                            ("parcelle_interest", "Intérêt pour une parcelle"),
                            ("match_found", "Correspondance trouvée"),
                            ("visit_request", "Demande de visite"),
                            ("visit_confirmed", "Visite confirmée"),
                            ("new_message", "Nouveau message"),
                            ("new_review", "Nouvel avis"),
                            ("client_request", "Demande client"),
                            ("kyc_update", "Mise à jour KYC"),
                            ("document_ready", "Document disponible"),
                            ("account_update", "Mise à jour compte"),
                            ("welcome", "Bienvenue"),
                            ("inactivity_reminder", "Rappel inactivité"),
                            ("newsletter", "Newsletter"),
                            ("system", "Système"),
                        ],
                        max_length=30,
                        verbose_name="type de notification",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("inapp", "In-App"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                            ("push", "Push"),
                        ],
                        max_length=10,
                        verbose_name="canal",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Objet de l'email ou titre de la notification",
                        max_length=300,
                        verbose_name="objet / titre",
                    ),
                ),
                (
                    "body_template",
                    models.TextField(
                        help_text="Texte du message. Utiliser la syntaxe Django template : {{ user_name }}, {{ parcelle_lot }}, {{ reference }}, {{ amount }}, {{ action_url }}",
                        verbose_name="corps du message",
                    ),
                ),
                (
                    "whatsapp_content_sid",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SID du template approuvé Meta/Twilio pour les messages WhatsApp hors fenêtre",
                        max_length=100,
                        verbose_name="Content SID WhatsApp",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="fr", max_length=10, verbose_name="langue"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Modèle de notification",
                "verbose_name_plural": "Modèles de notification",
                "ordering": ["notification_type", "channel"],
                "unique_together": {("notification_type", "channel", "language")},
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=300, verbose_name="nom de la campagne"),
                ),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("newsletter", "Newsletter"),
                            ("reengagement", "Ré-engagement"),
                            ("promotional", "Promotionnel"),
                        ],
                        default="newsletter",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "channels",
                    models.JSONField(
                        default=list,
                        help_text='Liste des canaux : ["email", "whatsapp", "sms"]',
                        verbose_name="canaux",
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("all", "Tous les utilisateurs"),
                            ("acheteurs", "Acheteurs"),
                            ("vendeurs", "Vendeurs / Propriétaires"),
                            ("inactive_30d", "Inactifs 30+ jours"),
                            ("custom", "Filtre personnalisé"),
                        ],
                        default="all",
                        max_length=20,
                        verbose_name="audience cible",
                    ),
                ),
                (
                    "custom_filter",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Filtre Django ORM sérialisé pour audience avancée",
                        verbose_name="filtre personnalisé",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="objet / titre"
                    ),
                ),
                ("body", models.TextField(blank=True, verbose_name="corps du message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("scheduled", "Planifiée"),
                            ("sending", "En cours d'envoi"),
                            ("sent", "Envoyée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="draft",
                        max_length=15,
                        verbose_name="statut",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="envoi planifié le"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="envoyée le"
                    ),
                ),
                (
                    "total_recipients",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total destinataires"
                    ),
                ),
                (
                    "total_sent",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total envoyés"
                    ),
                ),
                (
                    "total_delivered",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total délivrés"
                    ),
                ),
                (
                    "total_failed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total échoués"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créée par",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to="notifications.notificationtemplate",
                        verbose_name="modèle de message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campagne",
                "verbose_name_plural": "Campagnes",
                "ordering": ["-created_at"],
            },
        ),
    ]
